#!/usr/bin/env bash

set -o errexit
green='\033[0;32m'
no_color='\033[0m'

ok() {
    echo -e "$green$1$no_color"
}

ok "Beginning full e2e demo..."

ok "Installing gems..."
bundle install

ok "Starting gruf server..."
bundle exec gruf &
server_pid=$!

sleep 5 # let the server start
ok "Running unary test..."
bundle exec rake test:get_product
ok "Running server streamer test..."
bundle exec rake test:get_products
ok "Running client streamer test..."
bundle exec rake test:create_products
ok "Running bidi streamer test..."
bundle exec rake test:create_products_in_stream

ok "Tests successful! Shutting down server..."
kill -9 $server_pid
ok "Server shutdown, E2E demo finished successfully."
